### ISSUE TITLE
Restarting TV show via Chorus does not resume

### ISSUE THREAD

**Issue by un1versal** [jez500/chorus2#76]
Like that says, instead it starts playing from beginning.

**Comment by OliPassey** [comment]
Im seeing this issue when using switch player via json / upnp directly in kodi - havent tested in chrous yet though - i will take a look.
ive been told its due to a network issue my side, rather than the json call failing or being incorrect.
will be watching this thread for info (sorry for the hijack)

**Comment by un1versal** [comment]
It could be a bug Kodi side but since this is via json I wanted to get some feedback from jez500 first.

**Comment by OliPassey** [comment]
I had been troubleshooting with spud on the homeseer forums, think they are on kodi forums as well from time to time. 
Let me know if i can help test and get to the bottom of this one - its a feature im quite interested in having as it would allow me to use my home automation system to let playing content follow me around the house. but atm - it restarts any media rather than resuming.

http://board.homeseer.com/showthread.php?t=161819&page=9 Is the discussion point where i started asking for help in case it provides any more information

**Comment by OliPassey** [comment]
http://board.homeseer.com/showpost.php?p=1188974&postcount=209
Logs of the fail

**Comment by jez500** [comment]
I think there is 2 different issues here
@un1versal - This is on the todo list chorus1 does it, just requires work to implement.
@OliPassey - sounds like your issue is different, especially if occurs without using chorus

**Comment by un1versal** [comment]
OK thx.

**Comment by jez500** [comment]
@un1versal Added a nice ui for resuming videos

**Comment by un1versal** [comment]
Will be donwloading and testing it now :D

**Comment by un1versal** [comment]
Well that works 100% nice... congrats.
